[package]
name = "mambembe-cli"
version = "0.1.1"
authors = []
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
color-eyre = "0.5.10"
dotenv = "0.15.0"
fuzzy-matcher = "0.3.7"
mambembe-keyring = { path = "../keyring/" }
mambembe-lib = { path = "../lib" }
serde_json = "1.0.64"
structopt = "0.3.21"
tokio = { version = "1.8.4", features = ["full"] }
tracing = "0.1.25"
tracing-error = "0.1.2"
tracing-subscriber = { version = "0.2.17", features = ["fmt"] }

[features]
default = ["with-keyring"]
with-keyring = ["mambembe-keyring/with-keyring"]
without-keyring = ["mambembe-keyring/without-keyring"]
