[package]
name = "mambembe-keyring"
version = "0.1.1"
authors = ["Jayson Reis <santosdosreis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
directories = { version = "4.0.1", optional = true }
keyring = { version = "1.2.0", optional = true }
lazy_static = "1.4.0"
mambembe-lib = { path = "../lib" }
serde = "1.0.140"
serde_json = "1.0.105"
thiserror = "1.0.31"

[features]
with-keyring = ["keyring"]
without-keyring = ["directories"]
