[package]
name = "mambembe-stub-server"
version = "0.1.0"
authors = ["Jayson Reis <santosdosreis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
lazy_static = "1.4.0"
rand = "0.8.3"
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.64"
tide = "0.16.0"
tokio = { version = "1.2.0", features = ["rt-multi-thread", "macros"] }
url = "2.2.1"
